version: '3.1'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shorter_db
      PD_DATA: /var/lib/postgresql/data/data/
    ports:
      - 5431:5431
    volumes:
      - db:/var/lib/postgresql/data/data

volumes:
  db:
